# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookManager' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'
  pod 'SnapKit', '~> 4.0.0'
  pod 'MaterialComponents/Buttons+ButtonThemer'
  pod 'MaterialComponents/TextFields'

  # Pods for BookManager

  target 'BookManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BookManagerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
